In [1]:
# Liberias requeridas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
import itertools
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import tree
from sklearn.tree import export_graphviz
from sklearn import svm
from sklearn import neighbors
import io
import requests

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
mydata = pd.read_csv('structure_data.csv')
mydata.head()

Disk  Fibers  Micro      NSS1      NSS2      NSS3      NSS4
0     5       6      3 -3.184686  0.464171  2.014785 -0.286103
1     4       4      3 -3.876074 -0.545602  1.519739 -0.425403
2     5       6      3 -2.771356  0.991670  2.133971 -0.180300
3     4       6      3 -3.100863  0.567651  1.969417 -0.130916
4     5       6      3 -3.146888  0.504879  1.991486 -0.305380

In [3]:
mydata=mydata.iloc[:, [2,3,4,5,6]]
mydata.head() 

Micro      NSS1      NSS2      NSS3      NSS4
0      3 -3.184686  0.464171  2.014785 -0.286103
1      3 -3.876074 -0.545602  1.519739 -0.425403
2      3 -2.771356  0.991670  2.133971 -0.180300
3      3 -3.100863  0.567651  1.969417 -0.130916
4      3 -3.146888  0.504879  1.991486 -0.305380

In [4]:
mydata['Micro'].describe()


count    80.000000
mean      2.837500
std       0.371236
min       2.000000
25%       3.000000
50%       3.000000
75%       3.000000
max       3.000000
Name: Micro, dtype: float64

In [5]:
data, test= train_test_split(mydata, test_size = 0.3, random_state=0)
data.head()

Micro       NSS1      NSS2      NSS3      NSS4
55      3   0.111344  0.796861 -1.109148  0.545640
17      2  -4.361915 -2.074188 -1.052518  0.007060
60      3   2.645793  2.650672 -0.938823  0.805583
62      3   2.597513  2.530138 -0.704000 -0.271487
6       3  10.329673 -2.189068  0.343057 -0.416065

In [6]:
data = data.rename(columns = {data.columns.values[0]:'C'}) # Cambiamos el nombre de la última columna por "C" de clase
data.head()

C       NSS1      NSS2      NSS3      NSS4
55  3   0.111344  0.796861 -1.109148  0.545640
17  2  -4.361915 -2.074188 -1.052518  0.007060
60  3   2.645793  2.650672 -0.938823  0.805583
62  3   2.597513  2.530138 -0.704000 -0.271487
6   3  10.329673 -2.189068  0.343057 -0.416065

In [7]:
#data = data.apply(le.fit_transform) # Convertimos los valores de object a int
test.head()

Micro      NSS1      NSS2      NSS3      NSS4
50      3  1.693871  2.065955 -0.976759  0.741771
27      3  2.365539  2.308971 -0.527195 -0.516220
30      2 -5.298552 -3.355324 -1.052359 -0.306988
77      3 -3.838047 -0.427517  1.707117 -0.682892
45      3 -3.714805 -0.428853  1.087971  0.170843

In [8]:
test = test.rename(columns = {test.columns.values[0]:'C'}) # Cambiamos el nombre de la última columna por "C" de clase
test.head()

C      NSS1      NSS2      NSS3      NSS4
50  3  1.693871  2.065955 -0.976759  0.741771
27  3  2.365539  2.308971 -0.527195 -0.516220
30  2 -5.298552 -3.355324 -1.052359 -0.306988
77  3 -3.838047 -0.427517  1.707117 -0.682892
45  3 -3.714805 -0.428853  1.087971  0.170843

In [9]:
x_train = data.drop('C', axis = 1)
y_train = data['C']

#x_train
#y_train

x_test = test.drop('C', axis = 1)
y_test = test['C']

#x_test
#y_test


In [10]:
from collections import Counter

xs_trainval1, xs_testval1, ys_trainval1, ys_testval1 = train_test_split(x_train, y_train, test_size = 0.3, random_state=0)
print('Original dataset shape trainval {}'.format(Counter(ys_trainval1)))
print('Original dataset shape testval {}'.format(Counter(ys_testval1)))

Original dataset shape trainval Counter({3: 34, 2: 5})
Original dataset shape testval Counter({3: 13, 2: 4})


In [11]:
SVMl = svm.SVC(kernel='linear')

SVMl.fit(xs_trainval1, ys_trainval1)
SVMl_predict = SVMl.predict(xs_testval1)

print("\n############## Accuracy Linear SVM  ##################")
print(metrics.accuracy_score(ys_testval1, SVMl_predict))
print(metrics.confusion_matrix(ys_testval1, SVMl_predict))


############## Accuracy Linear SVM  ##################
0.941176470588
[[ 3  1]
 [ 0 13]]


In [12]:

SVMrbf = svm.SVC(kernel='rbf')

SVMrbf.fit(xs_trainval1, ys_trainval1)
SVMrbf_predict = SVMrbf.predict(xs_testval1)

print("\n############## Accuracy SVM RBF ##################")
print(metrics.accuracy_score(ys_testval1, SVMrbf_predict))
print(metrics.confusion_matrix(ys_testval1, SVMrbf_predict))


############## Accuracy SVM RBF ##################
0.941176470588
[[ 3  1]
 [ 0 13]]


In [13]:
SVMsg = svm.SVC(kernel='sigmoid')

SVMsg.fit(xs_trainval1, ys_trainval1)
SVMsg_predict = SVMsg.predict(xs_testval1)

print("\n############## Accuracy SVM sigmoid ##################")
print(metrics.accuracy_score(ys_testval1, SVMsg_predict))
print(metrics.confusion_matrix(ys_testval1, SVMsg_predict))


############## Accuracy SVM sigmoid ##################
0.764705882353
[[ 0  4]
 [ 0 13]]


In [14]:
SVMpoly = svm.SVC(kernel='poly')

SVMpoly.fit(xs_trainval1, ys_trainval1)
SVMpoly_predict = SVMpoly.predict(xs_testval1)

print("\n############## Accuracy SVM POLY ##################")
print(metrics.accuracy_score(ys_testval1, SVMpoly_predict))
print(metrics.confusion_matrix(ys_testval1, SVMpoly_predict))


############## Accuracy SVM POLY ##################
0.882352941176
[[ 3  1]
 [ 1 12]]


In [15]:
import statistics as stats
import pandas as pd

m=[]
M=[]
C=[]
report=[]
R=[]
for i in range(1,101):
    xs_train, xs_test, ys_train, ys_test = train_test_split(x_train, y_train, test_size = 0.4, random_state=None)
    SVMl1t = svm.SVC(kernel='rbf')
    SVMl1t.fit(xs_train, ys_train)
    SVMl1t_predict = SVMl1t.predict(xs_test)
    cm=metrics.confusion_matrix(ys_test, SVMl1t_predict)
    me=metrics.accuracy_score(ys_test, SVMl1t_predict)
    cr=metrics.classification_report(ys_test, SVMl1t_predict)
    report = pd.DataFrame(list(metrics.precision_recall_fscore_support(ys_test, SVMl1t_predict))).T
    m.append(me)
    M.append(cm)
    C.append(cr)
    R.append(report)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [16]:
Ra=np.array([])
Rb=np.array([])
Rc=np.array([])
Rd=np.array([])

for report in R:
    w=np.concatenate((report[0], report[1]), axis=None)
    Ra=np.append(Ra,w[0])
    Rb=np.append(Rb,w[1])
    Rc=np.append(Rc,w[2])
    Rd=np.append(Rd,w[3])

In [17]:
Re=np.array([])
Rf=np.array([])
Rg=np.array([])
Rh=np.array([])

for report in R:
    y=np.concatenate((report[2], report[3]), axis=None)
    Re=np.append(Re,y[0])
    Rf=np.append(Rf,y[1])
    Rg=np.append(Rg,y[2])
    Rh=np.append(Rh,y[3])

In [18]:
a=np.array([])
b=np.array([])
c=np.array([])
d=np.array([])

for m in M:
    v=np.concatenate((m[0], m[1]), axis=None)
    a=np.append(a,v[0])
    b=np.append(b,v[1])
    c=np.append(c,v[2])
    d=np.append(d,v[3])
print(a)
print(b)
print(c)
print(d)

[ 2.  3.  3.  3.  4.  3.  2.  3.  2.  2.  4.  2.  2.  2.  3.  3.  3.  3.
  3.  1.  4.  2.  3.  1.  3.  3.  3.  3.  0.  2.  3.  1.  4.  2.  2.  2.
  1.  2.  3.  3.  3.  1.  1.  2.  1.  2.  0.  1.  2.  2.  2.  2.  2.  4.
  2.  0.  3.  2.  3.  3.  3.  4.  4.  2.  2.  1.  4.  2.  0.  3.  2.  3.
  3.  1.  2.  4.  4.  4.  5.  2.  2.  4.  3.  3.  4.  2.  2.  2.  3.  2.
  2.  3.  3.  3.  2.  2.  2.  2.  0.  2.]
[ 0.  2.  1.  2.  1.  2.  2.  2.  1.  1.  0.  1.  3.  2.  1.  1.  2.  0.
  1.  1.  0.  0.  1.  1.  2.  1.  0.  1.  0.  1.  1.  0.  1.  2.  1.  2.
  1.  0.  1.  2.  0.  1.  2.  1.  0.  3.  1.  0.  1.  1.  0.  0.  0.  1.
  0.  6.  1.  1.  1.  2.  2.  0.  2.  1.  0.  0.  1.  0.  1.  0.  2.  1.
  2.  2.  2.  0.  0.  1.  1.  0.  0.  0.  1.  1.  0.  2.  2.  3.  0.  2.
  2.  2.  1.  1.  1.  3.  1.  1.  2.  1.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.
  1.  1.  1.  1.  0.  0.  0.  0.  1.  0.  1.  0.  0.  1.  0.  0.  0.  0.
  0.  1.  0.  1.  1.  0.  0.  1.  1.  0.

In [19]:
Ram=np.median(Ra)
Rbm=np.median(Rb)
Rcm=np.median(Rc)
Rdm=np.median(Rd)
Rem=np.median(Re)
Rfm=np.median(Rf)
Rgm=np.median(Rg)
Rhm=np.median(Rh)

#np.median(a)
Rad=np.std(Ra)
Rbd=np.std(Rb)
Rcd=np.std(Rc)
Rdd=np.std(Rd)
Red=np.std(Re)
Rfd=np.std(Rf)
Rgd=np.std(Rg)
Rhd=np.std(Rh)

In [20]:
print(Rad, Rcd, Red)
print(Rbd, Rdd, Rfd)

0.246735294507 0.251046476441 0.211443206242
0.0452154118597 0.0213105504358 0.0227586778976


In [21]:
A=np.median(a)
B=np.median(b)
C=np.median(c)
D=np.median(d)


In [22]:
print(A, B)
print(C, D)

2.0 1.0
0.0 19.0


In [23]:
print(Ram, Rcm, Rem) 
print(Rbm, Rdm, Rfm) 


1.0 0.666666666667 0.8
0.95 1.0 0.974358974359
