In [1]:
# Liberias requeridas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
import itertools
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import svm
from sklearn import neighbors
import io
import requests

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
mydata = pd.read_csv('GT_4NSS.csv')
mydata.head()

Number_Image  Disk  Fibers  Micro      Score  Number_eval      NSS1  \
0             1     5       6      3  60.733383           12 -3.184686   
1             2     4       4      3  57.166782           12 -3.876074   
2             3     5       5      3  59.713664           12 -2.771356   
3             4     5       5      3  56.423268           12 -3.100863   
4             5     4       4      3  54.409273           12 -3.146888   

       NSS2  Result_of_eval  type      NSS3      NSS4  
0  0.464171               1     1  2.014785 -0.286103  
1 -0.545602               1     1  1.519739 -0.425403  
2  0.991670               1     1  2.133971 -0.180300  
3  0.567651               1     1  1.969417 -0.130916  
4  0.504879               1     1  1.991486 -0.305380

In [3]:
mydata=mydata.iloc[:, [6,7,8,10,11]]
mydata.head() 

NSS1      NSS2  Result_of_eval      NSS3      NSS4
0 -3.184686  0.464171               1  2.014785 -0.286103
1 -3.876074 -0.545602               1  1.519739 -0.425403
2 -2.771356  0.991670               1  2.133971 -0.180300
3 -3.100863  0.567651               1  1.969417 -0.130916
4 -3.146888  0.504879               1  1.991486 -0.305380

In [4]:
mydata['Result_of_eval'].describe()


count    80.000000
mean      0.612500
std       0.490253
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000
Name: Result_of_eval, dtype: float64

In [5]:
data, test= train_test_split(mydata, test_size = 0.2, random_state=0)
data.head()

NSS1      NSS2  Result_of_eval      NSS3      NSS4
3   -3.100863  0.567651               1  1.969417 -0.130916
22  -5.381577 -3.491304               0 -1.097462 -0.318131
7   15.240882 -1.343729               1  0.754215 -0.207004
26  -5.203271 -3.205209               0 -1.063722 -0.241252
42  15.171896 -1.470034               1  0.384660  0.304700

In [6]:
data = data.rename(columns = {data.columns.values[2]:'C'}) # Cambiamos el nombre de la última columna por "C" de clase
data.head()

NSS1      NSS2  C      NSS3      NSS4
3   -3.100863  0.567651  1  1.969417 -0.130916
22  -5.381577 -3.491304  0 -1.097462 -0.318131
7   15.240882 -1.343729  1  0.754215 -0.207004
26  -5.203271 -3.205209  0 -1.063722 -0.241252
42  15.171896 -1.470034  1  0.384660  0.304700

In [7]:
test.head()

NSS1      NSS2  Result_of_eval      NSS3      NSS4
50  1.693871  2.065955               1 -0.976759  0.741771
27  2.365539  2.308971               1 -0.527195 -0.516220
30 -5.298552 -3.355324               0 -1.052359 -0.306988
77 -3.838047 -0.427517               1  1.707117 -0.682892
45 -3.714805 -0.428853               1  1.087971  0.170843

In [8]:
test = test.rename(columns = {test.columns.values[2]:'C'}) # Cambiamos el nombre de la última columna por "C" de clase
test.head()

NSS1      NSS2  C      NSS3      NSS4
50  1.693871  2.065955  1 -0.976759  0.741771
27  2.365539  2.308971  1 -0.527195 -0.516220
30 -5.298552 -3.355324  0 -1.052359 -0.306988
77 -3.838047 -0.427517  1  1.707117 -0.682892
45 -3.714805 -0.428853  1  1.087971  0.170843

In [9]:
x_train = data.drop('C', axis = 1)
y_train = data['C']

x_test = test.drop('C', axis = 1)
y_test = test['C']

In [10]:
from collections import Counter

xs_trainval1, xs_testval1, ys_trainval1, ys_testval1 = train_test_split(x_train, y_train, test_size = 0.2, random_state=0)
print('Original dataset shape trainval {}'.format(Counter(ys_trainval1)))
print('Original dataset shape testval {}'.format(Counter(ys_testval1)))

Original dataset shape trainval Counter({1: 29, 0: 22})
Original dataset shape testval Counter({1: 8, 0: 5})


In [11]:
SVMl = svm.SVC(kernel='linear')

SVMl.fit(xs_trainval1, ys_trainval1)
SVMl_predict = SVMl.predict(xs_testval1)

print("\n############## Accuracy Linear SVM  ##################")
print(metrics.accuracy_score(ys_testval1, SVMl_predict))
print(metrics.confusion_matrix(ys_testval1, SVMl_predict))


############## Accuracy Linear SVM  ##################
0.615384615385
[[1 4]
 [1 7]]


In [12]:

SVMrbf = svm.SVC(kernel='rbf')

SVMrbf.fit(xs_trainval1, ys_trainval1)
SVMrbf_predict = SVMrbf.predict(xs_testval1)

print("\n############## Accuracy SVM RBF ##################")
print(metrics.accuracy_score(ys_testval1, SVMrbf_predict))
print(metrics.confusion_matrix(ys_testval1, SVMrbf_predict))


############## Accuracy SVM RBF ##################
0.538461538462
[[1 4]
 [2 6]]


In [13]:
SVMsg = svm.SVC(kernel='sigmoid')

SVMsg.fit(xs_trainval1, ys_trainval1)
SVMsg_predict = SVMsg.predict(xs_testval1)

print("\n############## Accuracy SVM sigmoid ##################")
print(metrics.accuracy_score(ys_testval1, SVMsg_predict))
print(metrics.confusion_matrix(ys_testval1, SVMsg_predict))


############## Accuracy SVM sigmoid ##################
0.307692307692
[[2 3]
 [6 2]]


In [14]:
SVMpoly = svm.SVC(kernel='poly')

SVMpoly.fit(xs_trainval1, ys_trainval1)
SVMpoly_predict = SVMpoly.predict(xs_testval1)

print("\n############## Accuracy SVM POLY ##################")
print(metrics.accuracy_score(ys_testval1, SVMpoly_predict))
print(metrics.confusion_matrix(ys_testval1, SVMpoly_predict))


############## Accuracy SVM POLY ##################
0.538461538462
[[1 4]
 [2 6]]


In [15]:
import statistics as stats
import pandas as pd

m=[]
M=[]
C=[]
report=[]
R=[]
for i in range(1,101):
    xs_train, xs_test, ys_train, ys_test = train_test_split(x_train, y_train, test_size = 0.2, random_state=None)
    SVMl1t = svm.SVC(kernel='linear')
    SVMl1t.fit(xs_train, ys_train)
    SVMl1t_predict = SVMl1t.predict(x_test)
    cm=metrics.confusion_matrix(y_test, SVMl1t_predict)
    me=metrics.accuracy_score(y_test, SVMl1t_predict)
    cr=metrics.classification_report(y_test, SVMl1t_predict)
    report = pd.DataFrame(list(metrics.precision_recall_fscore_support(y_test, SVMl1t_predict))).T
    m.append(me)
    M.append(cm)
    C.append(cr)
    R.append(report)

In [16]:
a=np.array([])
b=np.array([])
c=np.array([])
d=np.array([])

for m in M:
    v=np.concatenate((m[0], m[1]), axis=None)
    a=np.append(a,v[0])
    b=np.append(b,v[1])
    c=np.append(c,v[2])
    d=np.append(d,v[3])
print(a)
print(b)
print(c)
print(d)

[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.
  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.
  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.
  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.
  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.
  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 2.  7.  2.  3.  2.  2.  2.  2.  7.  3.  2.  2.  3.  2.  2.  2.  2.  2.
  2.  2.  3.  7.  2.  2.  2.  2.  7.  2.  7.  2.  2.  2.  2.  2.  2.  2.
  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.

In [17]:
Ra=np.array([])
Rb=np.array([])
Rc=np.array([])
Rd=np.array([])

for report in R:
    w=np.concatenate((report[0], report[1]), axis=None)
    Ra=np.append(Ra,w[0])
    Rb=np.append(Rb,w[1])
    Rc=np.append(Rc,w[2])
    Rd=np.append(Rd,w[3])
print(Ra)
print(Rb)
print(Rc)
print(Rd)

[ 0.66666667  0.36363636  0.66666667  0.57142857  0.66666667  0.66666667
  0.66666667  0.66666667  0.36363636  0.57142857  0.66666667  0.66666667
  0.57142857  0.66666667  0.66666667  0.66666667  0.66666667  0.66666667
  0.66666667  0.66666667  0.57142857  0.36363636  0.66666667  0.66666667
  0.66666667  0.66666667  0.36363636  0.66666667  0.36363636  0.66666667
  0.66666667  0.66666667  0.66666667  0.66666667  0.66666667  0.66666667
  0.66666667  0.66666667  0.66666667  0.66666667  0.66666667  0.66666667
  0.66666667  0.66666667  0.66666667  0.66666667  0.66666667  0.57142857
  0.57142857  0.36363636  0.66666667  0.66666667  0.57142857  0.57142857
  0.66666667  0.66666667  0.57142857  0.66666667  0.66666667  0.66666667
  0.36363636  0.66666667  0.66666667  0.36363636  0.66666667  0.66666667
  0.66666667  0.36363636  0.36363636  0.66666667  0.66666667  0.66666667
  0.66666667  0.66666667  0.66666667  0.36363636  0.66666667  0.66666667
  0.36363636  0.66666667  0.57142857  0.66666667  0

In [18]:
Re=np.array([])
Rf=np.array([])
Rg=np.array([])
Rh=np.array([])

for report in R:
    y=np.concatenate((report[2], report[3]), axis=None)
    Re=np.append(Re,y[0])
    Rf=np.append(Rf,y[1])
    Rg=np.append(Rg,y[2])
    Rh=np.append(Rh,y[3])

In [19]:
Ram=np.median(Ra)
Rbm=np.median(Rb)
Rcm=np.median(Rc)
Rdm=np.median(Rd)
Rem=np.median(Re)
Rfm=np.median(Rf)
Rgm=np.median(Rg)
Rhm=np.median(Rh)

#np.median(a)
Rad=np.std(Ra)
Rbd=np.std(Rb)
Rcd=np.std(Rc)
Rdd=np.std(Rd)
Red=np.std(Re)
Rfd=np.std(Rf)
Rgd=np.std(Rg)
Rhd=np.std(Rh)

In [20]:
print(Rad, Rcd, Red)
print(Rbd, Rdd, Rfd)

0.102157017849 0.0 0.0893608772964
0.0 0.138734358478 0.106701897111


In [21]:
A=np.median(a)
B=np.median(b)
C=np.median(c)
D=np.median(d)


In [22]:
print(A, B)
print(C, D)

4.0 0.0
2.0 10.0


In [23]:
print(Ram, Rcm, Rem) 
print(Rbm, Rdm, Rfm) 

0.666666666667 1.0 0.8
1.0 0.833333333333 0.909090909091


In [24]:
Precision_mean=(Ram + Rbm) / 2
print(Precision_mean)

recall_m=(Rcm + Rdm) / 2
print(recall_m)

f1_score_m=(Rem + Rfm) / 2
print(f1_score_m)


0.833333333333
0.916666666667
0.854545454545
